apiVersion: v1
kind: Pod
metadata:
  name: thequoter-v2-sharedlb
  labels:
    app: thequoter
spec:
  containers:
  - name: thequoter
    image: pastjean/thequoter:v2
    ports:
    - name: http
      containerPort: 8080