apiVersion: v1
kind: Pod
metadata:
  name: thequoter-basic
  labels:
    app: thequoter-basic
spec:
  containers:
  - name: thequoter
    image: pastjean/thequoter:v1
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: thequoter-basic
spec:
  selector:
    app: thequoter-basic
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: http